import os

KAFKA_BOOTSTRAP=os.environ["KAFKA_BOOTSTRAP"]

EVENT_STREAMS_REST_API=os.environ["EVENT_STREAMS_REST_API"]

EVENT_STREAMS_API_KEY=os.environ["EVENT_STREAMS_API_KEY"]

TRAINING_TOPIC_NAME=os.environ["TRAINING_TOPIC_NAME"]
TEST_ARCHIVE_TOPIC_NAME=os.environ["TEST_ARCHIVE_TOPIC_NAME"]
TEST_STREAM_TOPIC_NAME=os.environ["TEST_STREAM_TOPIC_NAME"]

SCHEMA_ID=os.environ["SCHEMA_ID"]
SCHEMA_NAME=os.environ["SCHEMA_NAME"]
SCHEMA_FILE_NAME=os.environ["SCHEMA_FILE_NAME"]
SCHEMA_VERSION="1"

CERT="./es-cert.pem"
